title: Michael Lee 
description: >
    I'm currently a third year University of Toronto student enrolled in a computer science specialist, 
    along with a math and statistics minor. I have experience programming in Python, Java, C and Javascript, along with
    experience in developing with libraries such as React.
show_downloads: true
theme: jekyll-theme-cayman  