title: Michael Lee 
description: >
    I'm currently a fourth year University of Toronto student enrolled in a computer science specialist, 
    along with a math minor. I have experience programming in Python, Java, C/C++ and Javascript, along with
    experience in developing with libraries such as React.
show_downloads: true
theme: jekyll-theme-cayman  
